package com.idan.coupons.enums;

public enum InputErrorType {
	

	INVALID_NAME,
	INVALID_EMAIL,
	INVALID_PASSWORD,
	INVALID_START_DATE,
	INVALID_END_DATE,
	INVALID_AMOUNT,
	INVALID_MESSAGE,
	INVALID_PRICE,
	INVALID_END_BEFORE_START,
	INVALID_START_ALREADY_PASSED;

}
